### ISSUE TITLE
How to stop brute force Guesing of API keys

### ISSUE THREAD

**Issue by buddudevelopers** [meilisearch/MeiliSearch#1025]
On the MeiliSearch Dashboard, providing a valid API key will grant access to the entire database. How can one prevent a script attempting different combinations of characters to brute force the key in production? In other words is there a rate limiter?

**Comment by LegendreM** [comment]
hello @buddudevelopers, for the moment we don't have any rate-limiter  on meilisearch. We didn't decide if we want to implement it with other advanced authentication features or if we want to delegate it to another service like [kong](https://konghq.com/).
In one case it's simple for the user but need to be implemented, in an other case, using an open source service, it mutualize work and expertise.

If you want to try kong with meilisearch you can use the `rate-limiting` plugin easily with declarative configuration in Kong.
Here is an example of declarative configuration file:

```yaml
# ------------------------------------------------------------------------------
# This is an example file to get you started with using
# declarative configuration in Kong.
# ------------------------------------------------------------------------------

# Metadata fields start with an underscore (_)
# Fields that do not start with an underscore represent Kong entities and attributes

# _format_version is mandatory,
# it specifies the minimum version of Kong that supports the format

_format_version: "1.1"

# Each Kong entity (core entity or custom entity introduced by a plugin)
# can be listed in the top-level as an array of objects:

services:
- name: meilisearch
  # destination url where kong redirect if user is allowed
  url: http://localhost:7700

  routes:
  - name: base
    # host called by the user
    hosts: ["localhost:8000"]
    paths:
    - /
    strip_path: false
```
