### ISSUE TITLE
[Question] Search data accessed from multiple pods in Kubernetes cluster

### ISSUE THREAD

**Issue by otivvormes** [meilisearch/MeiliSearch#1111]
Hello,

Firstly thank you for developing this project, It's been great using it and I will be using it in my production application, so keep up the good work :)

I could not find similar issue addressed here, so I apologise if it actaully exists somewhere...

I intend to deploy MeiliSearch with Kubernetes on DigitalOcean with **nfs** volume so the search data can be shared accross multiple pods (but can it be?). So I have "PersistenceVolumeClaim" attached to the "Deployment", smth like this:

**Persistence volume claim**

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: search-nfs-data
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs
```

**Deployment**

```
spec:
  containers:
  - name: search-service
    image: getmeili/meilisearch:v0.16.0
    ports:
    - containerPort: 8080
    env:
    - name: MEILI_HTTP_ADDR
      value: 0.0.0.0:8080
    - name: MEILI_MASTER_KEY
      valueFrom:
        secretKeyRef:
          name: meili-secrets
          key: MEILI_API_KEY
    - name: MEILI_ENV
      value: production
    - name: MEILI_NO_ANALYTICS
      value:
    - name: MEILI_NO_SENTRY
      value:
    volumeMounts:
    - name: search-data
      mountPath: /data.ms
  volumes:
    - name: search-data
      persistentVolumeClaim:
        claimName: search-nfs-data
```

Everyting works fine if I'am using 1 replica of that pod, if I try to resize it to more that 1, the second pod doesn't deploys successfully, I guess it has something to do with multiple pods accessing the same db. 

The only log entry from the un-sucessfull pod `Error: heed error; Resource temporarily unavailable (os error 11)`.

I have read "https://github.com/meilisearch/MeiliSearch/issues/374#issuecomment-562511136" so my question is, how did you achieved that? Did you run everyting on one "Node" -> "Pod", or did you create some sort of volume with pods spread accross nodes which all access the same MeiliSearch database?

Thank you very much,

Regards
