### ISSUE TITLE
Heed error: Function not implemented (os error 38)

### ISSUE THREAD

**Issue by chaskett** [meilisearch/MeiliSearch#1195]
**Describe the bug**
Running the container fails due to 'heed error'. Changing version doesn't seem to make a difference. Perhaps related to underlying Rust function?

**To Reproduce**
Steps to reproduce the behaviour:
1. docker-compose.yml contains...
```
  search:
    image: getmeili/meilisearch:v0.18.1
    restart: always
    volumes:
      - ./data.ms:/data.ms
    ports:
      - 7700:7700
```
2. docker-compose up
In container log you will see... 
`Error: heed error; Function not implemented (os error 38)`
Have tested with image 0.13.0, 0.16.0, 0.17.0, and 0.18.1.  Using version 0.12.0 you will see a different error.

**Expected behavior**

**Desktop (please complete the following information):**
Docker Desktop, also reproducible on Google Cloud, Cloud Compute, VM Instance.
