### ISSUE TITLE
The ARM binary does not run on RHEL based ARM platform

### ISSUE THREAD

**Issue by kappa-wingman** [meilisearch/MeiliSearch#1410]
~/meilisearch-linux-armv8
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
memory allocation of 4 bytes failed
Aborted (core dumped)

For ARM platform, the page size for Ubuntu is 4KB.
The page szie for RHEL based Linux is 64KB.

Related info:
https://github.com/jemalloc/jemalloc/issues/467
https://github.com/fluent-plugins-nursery/td-agent-builder/issues/176

**Comment by kappa-wingman** [comment]
I compile it from source and I could run it but found another problem. Track it on #1411.

**Comment by curquiza** [comment]
Hello @kappa-wingman!! 🙂
Make the binary work for RHEL is not planned at the moment. You will need to compile from the source.

However we have a public roadmap where our users can share their ideas and their needs. It would be awesome if you can add your need so that other users will upvote it if they need it as well.
https://roadmap.meilisearch.com/tabs/5-ideas

I close this issue!

**Comment by curquiza** [comment]
@MarinPostma or @irevoire, WDYT?

**Comment by kappa-wingman** [comment]
Hello all

Since it use jemalloc-sys, it could use the environment variable "JEMALLOC_SYS_WITH_LG_PAGE=16" (https://docs.rs/crate/jemalloc-sys/0.3.2), which is similar to '--with-lg-page=16 for jemalloc).

I had forked the Meiliesearch and tried some GitHub Actions. The resulting binary could be run on AWS AMI 2 (4KB pagsize) and another ARM platform with RHEL (64KB pagesize). But I did not done any testing or know any performance implications.

Below is the GitHub actions for reference
I also updated the uraimo/run-on-arch-action version, the old version can't take the 'env' parameter)
Finally,  for the updated version, it also complained about architecture and distribution parameters are not valid.

```
on:
  release:
    types: [published]

name: Publish binaries to release

jobs:
  publish-armv8:
    name: Publish for ARMv8
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1.0.0
      - uses: uraimo/run-on-arch-action@v2.0.10
        id: runcmd
        with:
          architecture: aarch64 # aka ARMv8
          distribution: ubuntu18.04
          env: |
            JEMALLOC_SYS_WITH_LG_PAGE: 16
          run: |
            apt update
            apt install -y curl gcc make
            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal --default-toolchain stable
            source $HOME/.cargo/env
            cargo build --release --locked
      - name: Upload the binary to release
        uses: actions/upload-artifact@v1
        with:
          name: meilisearch-linux-armv8
          path: target/release/meilisearch
```
