### ISSUE TITLE
Clean persistent volume on Kubernetes cases an error

### ISSUE THREAD

**Issue by khash** [meilisearch/meilisearch#2166]
**Describe the bug**
Running the latest version of Meilisearch (0.25) on Kubernetes with a clean PVC mounted on `/data.ms` throws the error: _VERSION file not found or an older version was running. Use dump...._

However, the volume is new and empty. The only thing in the folder is `lost+found` folder added by default in Ubuntu. Removing `lost+found` folder solves the problem, but requires either a manual start of the container pod (to shell and remove the folder for the first time) or use of an init script to delete it.

**To Reproduce**
1. Deploy Meilisearch to a k8s, using a PVC mounted on `/data.ms`.

**Expected behavior**
Search daemon to start without errors.

**Meilisearch version:**
v0.25

**Comment by curquiza** [comment]
Hello @khash 

Looks like you upgraded your Meilisearch instance. Following the error message, you have to use a dump to apply the migration.
You might want to follow this guide: https://docs.meilisearch.com/learn/advanced/updating.html#update-to-the-latest-meilisearch-version

**Comment by khash** [comment]
This was not caused by an upgrade. The volume was new and empty. The only difference between when MS was showing the error and when it was not, was the presence of `lost+found` folder on an empty volume

**Comment by curquiza** [comment]
Oh ok sorry, I miss read the issue, my bad. Meilisearch cannot indeed read the DB (`data.ms`) if an unexpected folder has been put inside. Not sure this is something we can solve on our side.

**Comment by camsjams** [comment]
Had to downgrade to v0.24.0 to get Meilisearch to work on AWS and Google Cloud Kubernetes

**Comment by MihaiNueleanu** [comment]
@khash, great find! Thanks for sharing. I've been putting off upgrading from 0.24 because of this issue, though I never actually found the root cause until now. 

I've now added an init container to my kubernetes deployment which cleans up that directory and sure enough, it worked. In case you're curious:
```
      ...
      initContainers:
        - name: delete-lost-and-found
          image: busybox:1.34.1
          volumeMounts:
            - mountPath: "/data"
              name: mpvc-026
          command:
            - "sh"
            - "-c"
            - "cd /data && ls -lah && rm -rf lost+found"
```
