### ISSUE TITLE
docker compose not working

### ISSUE THREAD

**Issue by deroccha** [meilisearch/meilisearch#2292]
I have the following setting in my docker-compose 

```
  meilisearch:
    container_name: ${PROJECT_SUFFIX}_meilisearch
    image: getmeili/meilisearch:latest
    restart: always
    depends_on:
      - db
    volumes:
      - ./sql:/data.ms
    environment:
      MEILI_NO_ANALYTICS: 'true'
      MEILI_NO_SENTRY: 'true'
      MEILI_MASTER_KEY: null
      MEILI_ENV: 'development'
    ports:
      - target: 7700
        published: 7700
        protocol: tcp
```

on start will throw the following error :  **Error: Meilisearch (v0.26.1) failed to infer the version of the database. Please consider using a dump to load your data.**

I already cleaned up couple of times the shared Folder but the error persist.

**Comment by curquiza** [comment]
Hello @deroccha 

Have you updated the version of Meilisearch? The error message says you are trying to run Meilisearch with v0.26.1, but your documents have been added using an older version (like v0.25.0?).
Is it the case?

**Comment by deroccha** [comment]
@curquiza after upgrade I deleted the mounted folder and even  docker fully rested``docker system prune -u``

**Comment by oluademola** [comment]
Hi @deroccha If I understand you correctly, you've upgraded to version 0.26.1 of Meilisearch and now you're getting the following error: Error: Meilisearch (v0.26.1) failed to infer the version of the database. Please consider using a dump to load your data.
Have you tried removing specifically your database folder (data.ms) and using this version to reindex your documents all over again?

**Comment by deroccha** [comment]
Hi @curquiza I made a custom builded container and tagged that on build with the right platfom for M1 and now works. Previously I deleted all specific meilisearch data's but did not worked

**Comment by curquiza** [comment]
@deroccha glad to read you found out an issue. I'm a little bit annoyed since we did not succeed to reproduce your issue on our side (on M1).

If you have the time, can you share with us how you build it?

**Comment by fritzfr** [comment]
Hey,

I'm also encountering the error:

> Error: Function not implemented (os error 38)

while trying to build an arm64 docker image from `getmeili/meilisearch:v0.26.1`.

```
#9 [linux/arm64 1/3] FROM [docker.io/getmeili/meilisearch:v0.26.1@sha256:10f72ecdd219a54be8d3d17e231888047ec5bf1b38548f773880cbf8eaeb0f4a](http://docker.io/getmeili/meilisearch:v0.26.1@sha256:10f72ecdd219a54be8d3d17e231888047ec5bf1b38548f773880cbf8eaeb0f4a)
#9 extracting sha256:0857af6692e3c2c1b2d380b06b1a02b15a494c0b3300865af0300e4a6f0e2f90 0.2s done
#9 DONE 1.5s
#11 [linux/arm64 2/3] COPY [data.ms](http://data.ms/).snapshot /
#11 DONE 0.1s
#12 [linux/arm64 3/3] RUN ./meilisearch --no-analytics --ignore-snapshot-if-db-exists --import-snapshot data.ms.snapshot
#12 0.144 [2022-04-11T09:41:13Z INFO  meilisearch_lib::index_controller] Loading from snapshot "data.ms.snapshot"
#12 1.229 Error: Function not implemented (os error 38)
```

**Comment by curquiza** [comment]
Hello @fritzfr 

We have M1 internally and we did not succeed to reproduce your issue. Can you detail the commend you launched to have this problem?

**Comment by fritzfr** [comment]
Hey @curquiza 
I believe everything works fine on M1, I have an M1 Macbook too. The issue I am describing is happening **on a x86 machine**, that is our Gitlab runner. It has a pipeline that is building a multi-arch docker image using `docker buildx`.
The Dockerfile looks like this:

```docker
FROM getmeili/meilisearch:v0.26.1
COPY data.ms.snapshot /
RUN ./meilisearch --no-analytics --ignore-snapshot-if-db-exists --import-snapshot data.ms.snapshot 
```

and the Pipeline contains:
```yaml
variables:
  CONTAINER_RELEASE_IMAGE: ${CI_REGISTRY_IMAGE}
  CONTAINER_TAG_RELEASE_IMAGE: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}
  CONTAINER_PLATFORMS: linux/arm64,linux/amd64
```

```
    - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    - docker buildx create --use
    - docker buildx build --platform $CONTAINER_PLATFORMS --push --tag $CONTAINER_RELEASE_IMAGE .
```
