### ISSUE TITLE
Remove `--max-index-size` and `--max-task-db` configuration options

### ISSUE THREAD

**Issue by dureuill** [meilisearch/meilisearch#3231]
Following [Product discussion](https://github.com/meilisearch/product/discussions/567#discussioncomment-4322126)

Specification: https://github.com/meilisearch/specifications/pull/207
As part of the [CLI stabilization](https://github.com/meilisearch/meilisearch/issues/2752), we want to remove these options as we don't want to commit to them in their current shape for v1.

### Impacted teams

- @meilisearch/docs-team for sure
- I believe @meilisearch/cloud-team is using these options.
- Not sure if the integrations are impacted, however.

### Open questions

Before working on this, we need to resolve the following open questions positively:

1. Is Windows still pre-allocating map files for modern-day lmdb? It appears as if MacOS isn't.
2. Is lmdb taking more space than necessary when working with a large mapsize? We would need to benchmark this
3. We need another way to express the size available to soft-deleted documents, as it currently uses the --max-index-size option for this purpose

**Comment by dureuill** [comment]
> Is Windows still pre-allocating map files for modern-day lmdb? It appears as if MacOS isn't.

Here are the results of running meilisearch with various values of `--max-index-size`, on a W10 machine with 8GB of RAM and 50GB of disk space:

- 10TB or less: OK
- 11-13TB: strange error "An unexpected crash occurred when processing the task"
- 14-137TB: pagination error (os error 1455)
- 138-140TB: available memory resources are insufficient to handle this command (os error 8)
- 141TB or more: invalid parameter (os error 87)

**Comment by dureuill** [comment]
> 2. Is lmdb taking more space than necessary when working with a large mapsize? We would need to benchmark this

Benchmarked this 😎 

Ran locally on a macOS M1 machine with about 300GiB available disk space using the benchmark tool at https://github.com/meilisearch/ansible-vm-benchmarks/blob/indexing-tests with the following config.toml file:

```toml
[hosts]
[hosts.localhost-100GB]
host = "http://localhost:7700"

[hosts.localhost-10GB]
host = "http://localhost:7701"

[hosts.localhost-1GB]
host = "http://localhost:7702"

[hosts.localhost-1TB]
host = "http://localhost:7703"

[hosts.localhost-10TB]
host = "http://localhost:7704"

[tests]
[tests.several-indexing.hackernews-reset]
min_batch_size = "5MB"
max_batch_size = "5MB"
dataset = "/Users/dureuill/datasets/hackernews/data.ndjson"
reset_at_each_batch = true
iterations = 100

[tests.several-indexing.hackernews-noreset]
min_batch_size = "5MB"
max_batch_size = "5MB"
dataset = "/Users/dureuill/datasets/hackernews/data.ndjson"
reset_at_each_batch = false
iterations = 100
```

where each host was a meilisearch instance started with the `--max-index-size` option set to the value described in the host name.

Resulting in the following [report file](https://docs.google.com/spreadsheets/d/1u9Idkh_MDs-Jj47qleJCBi6r4Sq6lz_QhVd-LhjuVz0/edit?usp=sharing) (Google Sheets)

In particular we can see in the data that the disk space occupation profile seems independent from the `--max-index-size` parameter.
