### ISSUE TITLE
Authorization problem on Prometheus integration

### ISSUE THREAD

**Issue by konstantin83** [meilisearch/meilisearch#3879]
Hi! Thanks for such a great software!

I'm trying to monitor Meiliearch with Grafana via Prometheus.

My prometheus config:
```
global:
  scrape_interval:     15s
  external_labels:
    monitor: 'codelab-monitor'
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'meilisearch'

    scrape_interval: 5s
#    bearer_token: 'fvZJKS6DtD4ZAJSaUN8j37ksdkOhE6L69qwtD8Af5XM'
    authorization:
      credentials: 'fvZJKS6DtD4ZAJSaUN8j37ksdkOhE6L69qwtD8Af5XM'
    static_configs:
      - targets: ['localhost:7700']
```
Prometheus shows configuration as following:
```
global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 1m
  external_labels:
    monitor: codelab-monitor
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 5s
  scrape_timeout: 5s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - localhost:9090
- job_name: meilisearch
  honor_timestamps: true
  scrape_interval: 5s
  scrape_timeout: 5s
  metrics_path: /metrics
  scheme: http
  authorization:
    type: Bearer
    credentials: <secret>
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - localhost:7700
```

But "Targets" page in Prometheus shows that Meilisearch refused the connection
![prom](https://github.com/meilisearch/meilisearch/assets/13274062/f3246065-b316-46d2-a8a5-dcc7b4979994)

Meilisearch was started with this command:
`./meilisearch --master-key fvZJKS6DtD4ZAJSaUN8j37ksdkOhE6L69qwtD8Af5XM --experimental-enable-metrics`

What am I doing wrong?

Meilisearch version: v1.2
on Ubuntu 22.04.2 LTS
