### ISSUE TITLE
Importing larger dump fails with No file descriptors available

### ISSUE THREAD

**Issue by sznowicki** [meilisearch/meilisearch#4396]
**Describe the bug**
I have a "bigger" search indexes for my [search engine](https://kukei.eu). 

There are 3 indexes. From 14K, through 43K up to 755K documents:
<img width="238" alt="Bildschirmfoto 2024-02-08 um 09 33 19" src="https://github.com/meilisearch/meilisearch/assets/3393569/ff982499-67b8-48ef-bb99-2e6912dc2097">

`data.ms` file with 1.5.1 takes around 77GB on disk. Dump just 1.5G.

When I import it to 1.6.1 it succeeds with the smaller indexes, but fails with the bigger one with a following debug log:

```
meili-161  | [2024-02-08T08:31:25Z DEBUG TimerFinished] IndexDocuments::execute_raw(), Elapsed=313.03832227s
meili-161  | [2024-02-08T08:31:25Z DEBUG TimerFinished] IndexDocuments::execute(), Elapsed=761.179950715s
meili-161  | Error: No file descriptors available (os error 24)
```

Full log attached: [docker-compose-log.txt](https://github.com/meilisearch/meilisearch/files/14206332/docker-compose-log.txt)

Also I'm happy to share with you the dump file over some private channel for easier repro.

**To Reproduce**
1. Follow the update Meilisearch steps (docker type) with my dump file (I use docker compose for convenience but result should be the same as `docker run`
2. Observe logs
3. Import fails with above error

**Expected behavior**
Import finishes without an error

**Meilisearch version:**
1.6.1

**Additional context**
Machine is a self hosted PC with ubuntu/docker setup (disk is 1T SSD, exFat mount, 16GB RAM). I can try to reproduce it on Hetzner VPS as well if it helps.

**Comment by Kerollmops** [comment]
Hello @sznowicki 👋

Thank you very much for this report. The error you got seems related to the number of opened file descriptors. Meilisearch loves to open many files. We are working on this in #4350, and [there is a dedicated documentation page](https://www.meilisearch.com/docs/learn/advanced/known_limitations#large-datasets-and-internal-errors) about increasing the default limit for this value.

> Error: No file descriptors available (os error 24)

Could you run the following command before running Meilisearch, please? You must be in the same terminal session for it to work. You can replace 3000 with an even higher number if the issue persists.

```bash
ulimit -Sn 3000
```

I hope it fixes the issue. Please come back to me if it persists.
Have a nice day 🌻

**Comment by sznowicki** [comment]
Hi @Kerollmops 

I changed ulimit to 4000 (seems like a max for my OS) but no luck. Also set this up in docker-compose.yml to ensure it's actually really seen by the docker process.

I'm trying out putting some limits on meili itself via ENV hoping this would make the import process not open that many file descriptors.

```
MEILI_EXPERIMENTAL_MAX_NUMBER_OF_BATCHED_TASKS=50
MAX_INDEXING_MEMORY='2Gb'
```

**Comment by dureuill** [comment]
hello, 

I had some indexing operations require up to 30000 simultaneous file descriptors.
If using docker, make sure the limit is effective both inside and outside the docker.

**Comment by sznowicki** [comment]
Thx for the tip! Indeed bumping via `ulimit -Sn 400000` and setting up docker-compose.yml as attached seems to do the job. data.ms already is 9GB and counting.



```
version: "3"
services:
  meili161:
    image: getmeili/meilisearch:v1.6.1
    container_name: "meili-161"
    ulimits:
      nofile:
        soft: 400000
        hard: 500000
    volumes:
      - ./meili_data:/meili_data
#    network_mode: "host"
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 7701:7700
    command: > 
      sh -c "ulimit -n && meilisearch --import-dump /meili_data/dumps/dump.dump"
```

BTW: many thanks for making Meilisearch such a great project! I'm using it for a month or two and I'm absolutely in love with it!
