### ISSUE TITLE
"message": "internal: Error while generating embeddings: error: fetching file from HG_HUB failed: I/O error Read-only file system (os error 30).",

### ISSUE THREAD

**Issue by lodashventure** [meilisearch/meilisearch#4452]
Error :   
```
"message": "internal: Error while generating embeddings: error: fetching file from HG_HUB failed: I/O error Read-only file system (os error 30).",
```

**To Reproduce**
Step 1 : setting 
```
curl --location --request PATCH 'https://x-1.mei.com/indexes/hhg/settings' \
--header 'Content-Type: application/json' \
--data-raw '{
    "embedders": {
      "default": {
        "source": "huggingFace",
        "model": "BAAI/bge-base-en-v1.5"
      }
    }
  }'
```
Step 2 : index
```
curl 'https://x-1.mei.com/indexes/hhg/documents' \
  -H 'authority: x-1.mei.com' \
  -H 'accept: application/json' \
  --data-raw '[{"id":1233,"name":"tt"}]' \
 ```
 Error : 
 ```
 {
  "indexUid": "hhg",
  "status": "failed",
  "type": "documentAdditionOrUpdate",
  "uid": 628,
  "details": {
    "receivedDocuments": 1,
    "indexedDocuments": 0
  },
  "canceledBy": null,
  "error": {
    "message": "internal: Error while generating embeddings: error: fetching file from HG_HUB failed: I/O error Read-only file system (os error 30).",
    "code": "internal",
    "type": "internal",
    "link": "https://docs.meilisearch.com/errors#internal"
  },
  "duration": "PT0.349254532S",
  "startedAt": "2024-02-28T20:47:16.356Z",
  "enqueuedAt": "2024-02-28T20:47:16.247Z",
  "finishedAt": "2024-02-28T20:47:16.705Z"
}
```

**Screenshots**
<img width="967" alt="Screen Shot 2567-02-29 at 03 51 31" src="https://github.com/meilisearch/meilisearch/assets/59624681/22133408-a1c2-43e6-b627-24ce03fed865">

**Meilisearch version:**
[e.g. v1.6.0]

K8S HelmChart Default yaml
ref : https://github.com/meilisearch/meilisearch-kubernetes/blob/main/charts/meilisearch/values.yaml

**Comment by dureuill** [comment]
Hello :wave:

Can you retry by modifying the yaml to add:

```yaml
# Environment loaded into the configMap
environment:
  # -- Deactivates analytics
  MEILI_NO_ANALYTICS: true
  # -- Sets the environment. Either **production** or **development**
  MEILI_ENV: development
  # For production deployment, the environment MEILI_MASTER_KEY is required.
  # If MEILI_ENV is set to "production" without setting MEILI_MASTER_KEY, this
  # chart will automatically create a secure MEILI_MASTER_KEY and push it as a
  # secret. Otherwise the below value of MEILI_MASTER_KEY will be used instead.
  # MEILI_MASTER_KEY: ""
   HF_HOME: /meili_data/hf_home
```

?

Ref: https://huggingface.co/docs/huggingface_hub/package_reference/environment_variables#hfhome
