### ISSUE TITLE
After data was inserted in batches, the memory leaked, and the memory was not released, and it was occupied all the time

### ISSUE THREAD

**Issue by Xuzan9396** [meilisearch/meilisearch#5219]
docker-compose.yaml
```
version: '3.9'

services:
  meilisearch:
    image: getmeili/meilisearch:v1.12
    container_name: meilisearch
    ports:
      - "7700:7700" # 将容器的 7700 端口映射到主机
    volumes:
      - ./meili_data:/meili_data # 挂载数据目录，确保数据持久化
    environment:
      - MEILI_MASTER_KEY=xxxxx # 替换为你的主密钥
      - MEILI_MAX_INDEXING_MEMORY=1Gb
    restart: unless-stopped # 配置自动重启策略
```

![image](https://github.com/user-attachments/assets/6ba993bc-09ef-4bd9-86fa-dc178c9b6b19)

As shown in the figure, no new data is inserted, but memory is still occupied, and the environment variable does not take effect

<img width="485" alt="image" src="https://github.com/user-attachments/assets/7e70b47a-1712-48af-b3a5-9abf22c310eb" />
