### ISSUE TITLE
Error: Resource busy (os error 16) when importing dumps

### ISSUE THREAD

**Issue by miiton** [meilisearch/meilisearch#5283]
A similar issue: #1833

**Describe the bug**

I encountered the error mentioned in the title while trying to import a dump file to instance on docker environment.

```
Error: Resource busy (os error 16) when importing dumps
```

**To Reproduce**
1. Export a dump file from the production environment.
2. Downloaded the dump file to my local environment
3. `docker compose cp ./20250126-071704960.dump meilisearch:/meili/dumps/20250126-071704960.dump`
4. `docker compose down`
5. `docker volume rm myprj_meili-data`
6. set `MEILI_IMPORT_DUMP` to `/meili/dumps/20250126-071704960.dump`
7. `docker compose up`
8. The error occurred.

**Expected behavior**

The dump file that caused the error is **404MB** , which is a fairly large size. I successfully imported a **38MB** dump file obtained from the same environment in the past, so I suspect that the error might be related to the larger size of the dump file. Could this be the case?
Unfortunately, I am unable to provide the production dump file due to its nature, but I wanted to report this as a first step.

**Meilisearch version:**

- Dump export source: v1.10.0
- Dump import targets: v1.10.0, v1.12.7 (both resulted in the same error)

**Comment by irevoire** [comment]
Hey @miiton,

I looked at https://github.com/meilisearch/meilisearch/issues/1833, but I don't think it's the same in the end 🤔 
This one happened because Meilisearch was moving a file between two partitions. Whatever the size of your dump, that triggered the error, which is not the case here, from what I understand.

Can you confirm that you did the exact same actions with the small dump that worked and the big one?

I'm not 100% sure what you're doing with docker-compose, but can you help me understand?

```
# What is `cp` doing here? You're moving the dump out of the docker volume to your local data?
docker compose cp ./20250126-071704960.dump meilisearch:/meili/dumps/20250126-071704960.dump
# Then you stops meilisearch
docker compose down
# Then rm the volume
docker volume rm myprj_meili-data
# Restart everything without making a new volume? How is the container accessing the dump?
```

Could you share the OS you're using? We already had this kind of issue with Windows a long time ago

**Comment by miiton** [comment]
Hi @irevoire 🖐️

Thank you for your reply.

> Can you confirm that you did the exact same actions with the small dump that worked and the big one?

Yes, I did the exact same actions.

> What is cp doing here?

I'm using this command to upload the dump file, which I downloaded from a remote server, to the Docker container.

The flow is:
```
[Remote Server] --> [My Local Machine (Host)] --> [My Local Docker Container]
```

> Then you stops meilisearch

I stop Meilisearch to enable the `MEILI_IMPORT_DUMP` environment variables to take effect.

> Then rm the volume

I remove the main data volume to allow the dump to be imported cleanly.

> Restart everything without making a new volume? How is the container accessing the dump?

Running `docker compose up` automatically creates a fresh volume.

> OS

I am indeed using Windows.
My environment is Windows 11 + Docker Desktop + WSL2.



Here is the relevant part of the docker-compose.yml.

```yaml
meilisearch:
  image: "getmeili/meilisearch:v1.12.7"
  ports:
    - "7700:7700"
  volumes:
    - "meili-data:/meili/data"
    - "meili-dumps:/meili/dumps"
    - "meili-snapshots:/meili/snapshots"
  healthcheck:
    test:
      ["CMD-SHELL", 'curl http://localhost:7700/health | grep "available"']
    interval: 10s
    timeout: 5s
    retries: 5
  environment:
    MEILI_DB_PATH: "/meili/data"
    MEILI_ENV: development
    MEILI_HTTP_ADDR: 0.0.0.0:7700
    MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
    MEILI_NO_ANALYTICS: false
    MEILI_DUMP_DIR: "/meili/dumps"
    MEILI_IMPORT_DUMP: "/meili/dumps/20250126-071704960.dump"
    MEILI_IGNORE_MISSING_DUMP: true
    MEILI_IGNORE_DUMP_IF_DB_EXISTS: true
    MEILI_LOG_LEVEL: INFO
    MEILI_MAX_INDEXING_MEMORY: 2Gb
    MEILI_MAX_INDEXING_THREADS: 2
    MEILI_HTTP_PAYLOAD_SIZE_LIMIT: 1Gb
    MEILI_SCHEDULE_SNAPSHOT: 3600
    MEILI_SNAPSHOT_DIR: "/meili/snapshots"
  logging:
    options:
      max-size: "10k"
      max-file: "5"
```
