### ISSUE TITLE
How it is supposed to use master key and api key in docker-compose file?

### ISSUE THREAD

**Issue by SiroDiaz** [meilisearch/MeiliSearch#605]
Hi,
i have in a docker-compose file MeiliSearch as a service and i want to set it to production. Reading the documentation i have no idea what is the key supposed to be (the master key i mean). I have put a string key using this format **xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx**.
My service is defined like this:

```yml
search_engine:
    image: getmeili/meilisearch:v0.10
    container_name: meilisearch
    restart: always
    depends_on:
      - mariadb
    volumes:
      - meilidata:/data.ms
    environment:
      - MEILI_API_KEY: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      - MEILI_MASTER_KEY: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      - MEILI_ENV: production
    ports:
      - 7700:7700
    networks:
      - app_net
```

I have tested that and many other ways but documentation doesn't help very much for Docker version.

Thanks.
