### ISSUE TITLE
Port 7700 not binding in production with Docker Swarm

### ISSUE THREAD

**Issue by SiroDiaz** [meilisearch/MeiliSearch#648]
Hi!

i can't create my index and schema in production via Postman/curl because the port 7700 is not being published. I have in my docker-compose.yml in the ports option 7700:7700 but i can't access to that port.
No log errors are thrown in the container with docker logs container_id. I'm using v0.10.
I had to downgrade to a previous version because search and indexing was not working.

Thanks.

**Comment by tpayet** [comment]
Hello @SiroDiaz,

If you run `docker run -p 7700:7700 --rm getmeili/meilisearch:v0.10`, can you reach the 7700 port?

Can you show me your `docker-compose.yml`?

**Comment by SiroDiaz** [comment]
> If you run docker run -p 7700:7700 --rm getmeili/meilisearch:v0.10, can you reach the 7700 port?

Not working. I have checked out the ufw (firewall) and i have allowed port 7700 so that can't be a problem. DB and app services are shared but only MeiliSearch doesn't publish it port.

> Can you show me your docker-compose.yml?

service definition:
```yml
search:
    image: getmeili/meilisearch:v0.10
    container_name: meilisearch
    restart: always
    depends_on:
      - mysqldb
    volumes:
      - meilidata:/data.ms
    environment:
      MEILI_MASTER_KEY: "xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx"
      MEILI_ENV: production
    ports:
      - 7700:7700
    networks:
      - app_net
```
Network definition:
```yml
networks:
  app_net:
    external:
      name: app_net
```
