### ISSUE TITLE
download_latest script randomly fails on GH actions with macos-latest

### ISSUE THREAD

**Issue by curquiza** [meilisearch/MeiliSearch#908]
In this really specific case:
- in CI
- using `macos-latest`

The script **randomly** fails because the `download_latest.sh` script is not able to identify the latest version.

<img width="1085" alt="Screenshot 2020-08-11 at 16 49 36" src="https://user-images.githubusercontent.com/20380692/90019189-5cf1eb80-dcae-11ea-80d0-55c6fc527925.png">

This fix would be useful for the meilsearch-swift CI.

**Comment by curquiza** [comment]
A temporary solution is:

```yml

name: MeiliSearch

on: push

jobs:
  download_latest:
    name: Download MeiliSearch latest
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: brew update && brew install meilisearch
      - run: meilisearch --no-analytics=true &
      - run: curl 'http://localhost:7700/version' #example
```

**Comment by Kerollmops** [comment]
Hum... I am not sure what happens here? Could you tell me more about that, please?

**Comment by curquiza** [comment]
The `download_script.sh` does not work every time (so fails randomly) in this GH Action configuration (notice the `macos-latest` usage):

```yml
name: MeiliSearch

on: push

jobs:
  download_latest:
    name: Download MeiliSearch latest
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: |                                                            # In the case it fails:
        curl -L https://install.meilisearch.com | sh # downloading MS with the script
        ls -la .                                                          # the meilisearch binary is here
        head -1 meilisearch                                    # the binary file contains "Not Found"
```

The script is able to detect the OS and the archi but, sometimes, not what is the tag of the latest (I don't know why...), so the download URL is incorrect, that's why there is "Not Found" in the downloaded binary file.
